#!/usr/bin/env bash

alias ls='ls -GFh'
alias rm='rm -i'
alias mv='mv -i'

alias cls='clear'

alias v='view'

alias gh='git push origin master'
alias gs='git status'
alias gu='git reset HEAD --'
alias gc='git commit'
