#!/usr/bin/env bash

alias ls='ls -GFh'
alias rm='rm -i'
alias mv='mv -i'

# Mac OSX doesn't have tac
alias tac='tail -rq'

alias cls='clear'

# Cheatsheets

alias v='view'
alias cs='cheatsheets'

# Git

alias ga='git add'
alias gh='git push origin master'
alias gs='git status'
alias gc='git commit'

# Ruby

alias rubies='rvm list'
alias gemsets='rvm gemset list'
alias gems='gem list'
